const NOT_FOUND = 404;

const SERVER_ERROR = 500;

const INVALID_DATA = 400;

const DUPE = 409;

const UNAUTHORIZED = 401;

module.exports = { NOT_FOUND, SERVER_ERROR, INVALID_DATA, DUPE, UNAUTHORIZED };
